name: CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --ignore-scripts
      - run: npm run build --if-present
        name: Build
      - run: npm test
        env:
          CI: true

  publish_tag_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}

      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main

      - run: |
          git config --global user.email "${{ github.actor }}@noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          echo "${{ steps.bump_version.outputs.tag }}"

      - run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm version --no-git-tag-version "${{ steps.bump_version.outputs.tag }}" && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
